### ISSUE TITLE
Redefine `require` so that it accepts coffescript modules

### ISSUE THREAD

**Issue by n-riesco** [n-riesco/jp-coffeescript#5]
See https://github.com/willwhitney/hydrogen/issues/139

On kernel startup, run:

``` javascript
require("coffee-script/register");
```

It looks like this is going to be a bit more involved than I initially thought; see:

http://coffeescript.org/documentation/docs/register.html

**Comment by slavaGanzin** [comment]
I pulled your changes from master and it doesns't work for me the same way as before:
https://github.com/willwhitney/hydrogen/issues/139#issuecomment-161397968

It can be reproduced in notebook and in hydrogen

**Comment by n-riesco** [comment]
The changes are already available from `npm` and they seem to work in my computer.

Please, could you install the `npm` package and check the installed version?

``` shell
$ npm i jp-coffeescript
jp-coffeescript@0.0.9 node_modules/jp-coffeescript
└── node-uuid@1.4.7
$ jp-coffee --version
0.0.9
```

If it's still failling, please could post here the error message?

**Comment by n-riesco** [comment]
I've just got this error message after further testing:

```

Error
Cannot find module 'atom-space-pen-views' Error: Cannot find module 'atom-space-pen-views'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/user/tmp/atom/hydrogen/lib/watch-sidebar.coffee:1:7)
at Object.<anonymous> (/home/user/tmp/atom/hydrogen/lib/watch-sidebar.coffee:1:1)
at Module._compile (module.js:456:26)
at Object.loadFile (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
at Module.load (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at evalmachine.<anonymous>:3:16
at run ([eval]:192:19)
at onMessage ([eval]:63:41)
at process.EventEmitter.emit (events.js:98:17)
at handleMessage (child_process.js:318:10)
at Pipe.channel.onread (child_process.js:345:11)
```

**Comment by n-riesco** [comment]
I've installed `npm i atom-space-pen-views` and now the error message is:

```

ReferenceError
document is not defined ReferenceError: document is not defined
at Object.<anonymous> (/home/nriesco/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:36:11)
at Object.<anonymous> (/home/nriesco/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:634:4)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/nriesco/node_modules/atom-space-pen-views/lib/main.js:4:10)
at Object.<anonymous> (/home/nriesco/node_modules/atom-space-pen-views/lib/main.js:22:4)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/nriesco/tmp/atom/hydrogen/lib/watch-sidebar.coffee:1:7)
at Object.<anonymous> (/home/nriesco/tmp/atom/hydrogen/lib/watch-sidebar.coffee:1:1)
at Module._compile (module.js:456:26)
at Object.loadFile (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
at Module.load (/home/nriesco/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at evalmachine.<anonymous>:3:16
at run ([eval]:192:19)
at onMessage ([eval]:63:41)
at process.EventEmitter.emit (events.js:98:17)
at handleMessage (child_process.js:318:10)
at Pipe.channel.onread (child_process.js:345:11)
```

**Comment by n-riesco** [comment]
As you see, now the problem is that the `document` object is not defined in a Node.js session.

I'm not sure how to work around `document` not being defined.

**Comment by slavaGanzin** [comment]
> I've just got this error message after further testing
> `Cannot find module 'atom-space-pen-views' Error: Cannot find module 'atom-space-pen-views'`

Sorry for delay in answers. That's ok. Because node env and atom env is different. That isn't an issue.

**Comment by slavaGanzin** [comment]
I change DEBUG to true and get this:

`KERNEL: STARTUP: 'require("coffee-script/register");' failed to run`

**Comment by slavaGanzin** [comment]
Ah, I see. It want's coffee-script installed locally. Can we `require` from global packages? Or even better require from jp-coffeescript node_modules?

**Comment by n-riesco** [comment]
Could you run `require("coffee-script/register")` in `node` and post the error here?

What version of version of `coffee-script` are you using?

```
$ coffee --version
CoffeeScript version 1.10.0
$ node
> require("coffee-script/register")
{}
> 
```

**Comment by slavaGanzin** [comment]
If I install coffee-script locally to project folder(like Hydrogen one) it works.

I have the same

```
$ coffee --version
CoffeeScript version 1.10.0
$ node
> require("coffee-script/register")
{}
> 
```

**Comment by slavaGanzin** [comment]
Ah sorry. If I launch it in home directory or any other where I have no node_modules/coffee-script it doesn't import:

```
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)

```

**Comment by slavaGanzin** [comment]
So we can programmaticaly launch `npm link coffee-script` before `require("coffee-script/registry")` and pollute every project. Or find a crossplatform way to require global  coffeescript package.

**Comment by slavaGanzin** [comment]
@n-riesco https://github.com/n-riesco/jp-coffeescript/pull/6 Works for me. Give a try

**Comment by n-riesco** [comment]
For the time being, I'd rather recommend to install `jp-coffeescript` along with `coffee-script`:

```
npm i jp-coffeescript coffee-script
```

I'm thinking of using `require.resolve("coffee-script")` to get the location of the `coffee-script` module.

**Comment by slavaGanzin** [comment]
So what Nicolas?
is `require.resolve` acceptable?

**Comment by n-riesco** [comment]
@terraqout Yes, it does. I've already merged your PR. Thanks.

**Comment by slavaGanzin** [comment]
Thanks for your time
